const fruits = [
  "apples",
  "arugula",
  "asparagus",
  "artichoke",
  "avocado",
  "bananas",
  "blueberries",
  "broccoli",
  "carrots",
  "celery",
  "cherries",
  "cauliflower",
  "daikon radish",
  "dip",
  "eggplant",
  "edemame",
  "endive",
  "figs",
  "fava beans",
  "grapes",
  "grapefruit",
  "guava",
  "garlic",
  "ginger",
  "honeydew melon",
  "raisins",
  "raspberries",
  "radishes",
  "romaine lettuce",
  "spinach",
  "squash",
  "sprouts",
  "strawberries",
  "sunflower seeds",
  "tangerine",
  "tropical fruit",
  "turnips",
  "tomatillos",
  "turnip greens",
  "ugli fruit",
  "vine ripe tomatoes",
  "watermelon",
  "walnuts",
  "watercress",
  "woodear mushrooms",
  "yams",
  "yukon gold potatoes",
  "quince",
  "peas",
  "peppers",
  "pineapple",
  "pears",
  "peaches",
  "oranges",
  "onions",
  "oyster mushrooms",
  "okra",
  "nectarines",
  "nuts",
  "mushrooms",
  "melon",
  "mangos",
];

export default fruits;